# Generated by Django 5.0.7 on 2024-07-27 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
